project:
  type: website
  output-dir: _site

website:
  title: "Josh’s Blog"
  navbar:
    left:
      - text: "Home"
        file: posts/index.qmd
    right:
      - text: "About"
        file: posts/about.qmd
      - text: "Blog"
        file: posts/posts.qmd

