project:
  type: website
  output-dir: _site

website:
  title: "Josh’s Blog"
  favicon: images/favicon.ico
  navbar:
    left:
      - text: "Home"
        href: index.html
    right:
      - text: "Archive Vault"
        href: archive/archive.html
      - text: "Posts"
        href: posts/posts.html

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    respect-user-color-scheme: true
    toc: true                     # show a TOC sidebar on wide screens
    toc-depth: 2
    code-fold: true               # allow hiding/showing code blocks
    code-tools: true

