---
title: Clean Code
description: A guide for making context-driven decisions about code quality
---

### What is the Goal of Clean Code?

Before we even start to talk about techniques its important to discuss why clean code techniques are so important. 

The words to describe why are Consistency, Maintainability, and Readability. When writing code you should strive for these as much as possible

> KEY WORD: "Possible" - Clean code should be a goal only with-in the constraints of your projects requirements. If you have an extremely tight timeline, require extremely low runtimes, or any other common requirement then do not scarifice those requirements for clean code.

#### Consistency

Consistency is important, especially as the number of engineers who work on the project increases. Inconsistent styling, organizing, and formatting can increase the time it takes to find specific code in a project. 

For example, I am debugging a problem with a service that I have never touched before the bug is an issue with some business logic that is causing the output to have a mismatch from the expected. When looking through the service code to understand what the current business logic is it becomes difficult to find if the file names, directory names, and location of logic is in completely different locations not only compared to other services but within this service itself too. If instead it was placed consistently I could quickly go to the specific level of logic im concerned with because I know where to expect this logic to live

#### Maintainability

Maintainability is important for future work, whether it is yourself or someone else. If doing a minor feature change requires a lot of code changes then your service is not maintainable. You want it to be easy to add future un-anticipated features, doing so makes the team more agile. Agility allows development to complete faster saving that sacred developer time.

#### Readability

Readability, similar to consistency, is about the ability to understand the code. Not only is finding the code important being able to follow the intention of the logic is extremely important. Authors like Kent Beck, Martin Fowler, and Robert Martin will say your code should read like a story, and to an extent they are right (Clean Code bad amirite???). Code that makes the logic easy to follow makes understanding faster, and faster understanding of code means faster onboarding for new team members or faster refresh for exisiting members (remember this includes YOU too).


### Structure

Structuring your project is a big piece of Consistency and Maintainability, and by this I mean how you structure your directories and files. 

```
Project/
|- processor/
  |- fileProcessor
|- helpers/
  |- fileHelper
|- util/
  |- fileformatter
```

```
Project/
|- service/
  |- fileRequestHandler
|- logic/
  |- fileUploadComponent
  |- fileDownloadComponent
  |- mapper/
    |- fileMapper
|- dependency/
  |- fileServiceAccessor
```

### Conditions

When possible, simplify your conditions. This can mean a lot of different things. Maybe pushing a complex condition to a succiently named method, or switching the type of condition (switch/case - nested if/else) can help increase the readability of the code.

#### Large Conditions

Complex conditions are the bane of readability and maintainability, remember that the reader of your code has to keep the entire context in their head (or context window if they are AI). When a long condition is checking for the same thing, (like if a user is allowlisted) then the condition can be moved to an amptly named method. Doing so allows the reader to understand the intent of the conditions without needing to read the entire thing.

For example, lets look at a (semi) complex condition that is attempting to check if a user is allowlisted.
```
if (user.x == c1 or user.y == c2 or user.z == c3):
    ...logic...
```

If we put the condition into a separate method we remove the need to read the condition to understand the intent of the higher function.
```
if isUserAllowlisted():
    ...logic...

def isUserAllowlisted():
    return user.x == c1 or user.y == c2 or user.z == c3
```

#### Guard Clauses

This is something I got from Kent Beck's book "Tidy First". This trick moves conditions that guard logic to the top of the method, this helps show the conditions required for the method to continue.

As an example lets use the previously created isUserAllowlisted method.
```
def method(user):
    if isUserAllowlisted(user):
        ...logic...
```
With a single line this seems reasonable, but lets show what happens as the method grows (this is terrible code, just an example of how the structure of conditions gets worse over time)

```
def method(user):
    if isUserAllowlisted(user):
        state = getUserState(user)
        if isUserStateValid(state):
            ...logic...
        
```

This can then easily be replaced with guard clauses. These clauses make it easier to see what requirements are on the user or state in order to continue with the logic

```
def method(user):
    if !isUserAllowlisted(user):
        return or throw
    
    state = getUserState(user)

    if !isUserStateValid(state):
        return or throw
    
    ...logic...
```